
[target.x86_64-unknown-linux-gnu]
image = "secret-store-x86_64-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image = "secret-store-aarch64-linux-gnu"
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
	"RUSTFLAGS",
	"SKIP_WASM_BUILD",
]

[target.arm-unknown-linux-gnueabihf]
image = "secret-store-arm-linux-gnueabihf"
[target.arm-unknown-linux-gnueabihf.env]
passthrough = [
	"RUSTFLAGS",
	"SKIP_WASM_BUILD",
]

[target.armv7-unknown-linux-gnueabihf]
image = "secret-store-armv7-linux-gnueabihf"
[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
	"RUSTFLAGS",
	"SKIP_WASM_BUILD",
]